"use client";

import { useMemo, useState } from "react";
import { ArrowRight, Building2, Search, Ship, TicketCheck, UserRoundCheck } from "lucide-react";
import { useAdmin } from "@/components/admin/admin-provider";
import { Modal, StatusBadge } from "@/components/admin/ui";
import Dropdown from "@/components/ui/dropdown";
import { cn } from "@/lib/utils";

export default function ClientAssignmentsPage() {
  const { clients, employees, assignClient, auditEvents } = useAdmin();
  const [query, setQuery] = useState("");
  const [transferId, setTransferId] = useState<string | null>(null);
  const [assigneeId, setAssigneeId] = useState("");
  const activeEmployees = employees.filter((employee) => !employee.isSuperAdmin && employee.status !== "Disabled");
  const filtered = useMemo(() => clients.filter((client) => `${client.name} ${client.code} ${client.city}`.toLowerCase().includes(query.toLowerCase())), [clients, query]);
  const selected = clients.find((client) => client.id === transferId);
  const employeeName = (id: string) => employees.find((employee) => employee.id === id)?.name ?? "Unassigned";
  const history = selected ? auditEvents.filter((event) => event.entityId === selected.id && event.action === "Transferred client").slice(0, 3) : [];
  function openTransfer(clientId: string, currentId: string) { setTransferId(clientId); setAssigneeId(currentId); }
  function confirm() { if (selected && assigneeId) assignClient(selected.id, assigneeId); setTransferId(null); }
  return <div className="w-full"><div><h1 className="text-2xl font-semibold tracking-[-0.03em]">Client assignments</h1><p className="mt-1 text-sm text-muted-foreground">Control operational responsibility without changing acquisition attribution.</p></div>
    <section className="mt-6 grid gap-3 md:grid-cols-3">{[{ label: "Assigned clients", value: clients.length, icon: Building2 }, { label: "Shipment volume", value: clients.reduce((sum, client) => sum + client.shipmentVolume, 0), icon: Ship }, { label: "Open support tickets", value: clients.reduce((sum, client) => sum + client.openTickets, 0), icon: TicketCheck }].map(({ label, value, icon: Icon }) => <article key={label} className="flex items-center gap-4 rounded-xl border border-border bg-card p-4 shadow-xs"><div className="grid size-10 place-items-center rounded-xl bg-primary/10 text-primary"><Icon className="size-[18px]" /></div><div><p className="text-xl font-semibold">{value}</p><p className="text-xs text-muted-foreground">{label}</p></div></article>)}</section>
    <section className="mt-4 overflow-hidden rounded-xl border border-border bg-card shadow-xs"><div className="border-b border-border/60 p-4"><div className="relative max-w-md"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><input value={query} onChange={(event) => setQuery(event.target.value)} className="h-10 w-full rounded-xl border border-border pl-9 pr-3 text-sm outline-none focus:border-primary focus:ring-4 focus:ring-primary/10" placeholder="Search client, code, or city" /></div></div><div className="overflow-x-auto"><table className="w-full min-w-[1100px] text-left"><thead><tr className="border-b border-border/60 bg-muted/60 text-[10px] font-bold uppercase tracking-[0.1em] text-muted-foreground">{["Client", "Current owner", "Onboarded by", "Activity", "Workload", "Status", ""].map((header) => <th key={header} className="px-4 py-3">{header}</th>)}</tr></thead><tbody className="divide-y divide-border/60">{filtered.map((client) => <tr key={client.id} className="hover:bg-muted/60"><td className="px-4 py-4"><p className="text-sm font-semibold">{client.name}</p><p className="mt-0.5 text-[11px] text-muted-foreground">{client.code} · {client.city}</p></td><td className="px-4 py-4"><div className="flex items-center gap-2"><div className="grid size-7 place-items-center rounded-lg bg-primary/10 text-[9px] font-bold text-primary">{employeeName(client.assignedToEmployeeId).split(" ").map((part) => part[0]).slice(0, 2).join("")}</div><span className="text-xs font-semibold text-foreground/80">{employeeName(client.assignedToEmployeeId)}</span></div></td><td className="px-4 py-4 text-xs text-muted-foreground">{employeeName(client.onboardedByEmployeeId)}</td><td className="px-4 py-4 text-xs text-muted-foreground">{client.lastActivity}</td><td className="px-4 py-4"><div className="flex gap-3 text-[11px]"><span><strong className="text-foreground">{client.shipmentVolume}</strong> shipments</span><span><strong className={cn(client.openTickets > 2 && "text-destructive")}>{client.openTickets}</strong> tickets</span></div></td><td className="px-4 py-4"><StatusBadge tone={client.status === "Active" ? "positive" : "warning"}>{client.status}</StatusBadge></td><td className="px-4 py-4"><button onClick={() => openTransfer(client.id, client.assignedToEmployeeId)} className="flex items-center gap-1.5 rounded-lg border border-border px-3 py-2 text-[11px] font-semibold text-muted-foreground hover:bg-muted/40">Transfer <ArrowRight className="size-3" /></button></td></tr>)}</tbody></table></div></section>
    <Modal open={Boolean(selected)} onClose={() => setTransferId(null)} title="Transfer client responsibility" description="The onboarding attribution will remain unchanged."><div className="rounded-xl bg-muted/40 p-4"><p className="text-sm font-semibold">{selected?.name}</p><div className="mt-2 flex items-center gap-2 text-xs text-muted-foreground"><span>{employeeName(selected?.assignedToEmployeeId ?? "")}</span><ArrowRight className="size-3.5" /><span className="font-semibold text-primary">{employeeName(assigneeId)}</span></div></div><div className="mt-5"><p className="mb-2 text-xs font-semibold text-foreground/80">New responsible employee</p><Dropdown label="Select responsible employee" value={assigneeId} onChange={setAssigneeId} options={activeEmployees.map((employee) => ({ value: employee.id, label: `${employee.name} · ${clients.filter((client) => client.assignedToEmployeeId === employee.id).length} clients` }))} /></div>{history.length > 0 && <div className="mt-5 border-t border-border/60 pt-4"><p className="text-xs font-semibold text-foreground/80">Recent assignment history</p>{history.map((event) => <p key={event.id} className="mt-2 text-[11px] text-muted-foreground">{event.before} → {event.after} · {new Date(event.timestamp).toLocaleDateString("en-IN")}</p>)}</div>}<div className="mt-6 flex justify-end gap-2"><button onClick={() => setTransferId(null)} className="h-9 rounded-md border border-input bg-background px-3 text-sm font-medium shadow-xs hover:bg-accent">Cancel</button><button disabled={!assigneeId || assigneeId === selected?.assignedToEmployeeId} onClick={confirm} className="flex h-9 items-center gap-2 rounded-md bg-primary px-3 text-sm font-medium text-primary-foreground shadow-sm hover:bg-primary/90 disabled:opacity-40"><UserRoundCheck className="size-4" /> Confirm transfer</button></div></Modal>
  </div>;
}
