"use client";

import { useMemo, useState } from "react";
import { Check, KeyRound, Search, ShieldCheck, Users, X } from "lucide-react";
import { useAdmin } from "@/components/admin/admin-provider";
import { StatusBadge } from "@/components/admin/ui";
import { permissions } from "@/lib/admin-domain";
import { cn } from "@/lib/utils";

export default function RolesPage() {
  const { roles, employees, toggleRolePermission } = useAdmin();
  const [selectedId, setSelectedId] = useState("role-ops");
  const [query, setQuery] = useState("");
  const selected = roles.find((role) => role.id === selectedId) ?? roles[0];
  const grouped = useMemo(() => Array.from(new Set(permissions.map((permission) => permission.group))).map((group) => ({ group, permissions: permissions.filter((permission) => permission.group === group && `${permission.label} ${permission.key}`.toLowerCase().includes(query.toLowerCase())) })).filter((item) => item.permissions.length), [query]);
  return <div className="flex min-h-full w-full flex-col"><div><h1 className="text-2xl font-semibold tracking-[-0.03em]">Roles & permissions</h1><p className="mt-1 text-sm text-muted-foreground">Define reusable access bundles and inspect effective coverage.</p></div>
    <div className="mt-6 grid min-h-0 flex-1 gap-4 xl:grid-cols-[320px_1fr]">
      <aside className="h-fit rounded-xl border border-border bg-card p-3 shadow-xs"><div className="px-2 pb-3 pt-1"><p className="text-xs font-semibold text-foreground">Organization roles</p><p className="mt-1 text-[11px] text-muted-foreground">{roles.length} reusable access profiles</p></div><div className="space-y-1">{roles.map((role) => { const count = employees.filter((employee) => employee.roleId === role.id).length; return <button key={role.id} onClick={() => setSelectedId(role.id)} className={cn("w-full rounded-xl border p-3 text-left transition", selected.id === role.id ? "border-primary/20 bg-primary/10" : "border-transparent hover:bg-muted/40")}><div className="flex items-center gap-3"><div className={cn("grid size-9 place-items-center rounded-xl", selected.id === role.id ? "bg-primary text-primary-foreground" : "bg-muted text-muted-foreground")}><ShieldCheck className="size-4" /></div><div className="min-w-0 flex-1"><p className="truncate text-xs font-semibold text-foreground">{role.name}</p><p className="mt-0.5 text-[10px] text-muted-foreground">{count} {count === 1 ? "employee" : "employees"}</p></div></div></button>; })}</div></aside>
      <section className="min-w-0 overflow-hidden rounded-xl border border-border bg-card shadow-xs"><div className="border-b border-border/60 p-5"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><div className="flex items-center gap-2"><h2 className="text-lg font-semibold tracking-tight">{selected.name}</h2>{selected.id === "role-super" && <StatusBadge tone="navy">System privilege</StatusBadge>}</div><p className="mt-1 max-w-xl text-xs leading-5 text-muted-foreground">{selected.description}</p><div className="mt-3 flex gap-4 text-[11px] text-muted-foreground"><span className="flex items-center gap-1.5"><Users className="size-3.5" />{employees.filter((employee) => employee.roleId === selected.id).length} assigned</span><span className="flex items-center gap-1.5"><KeyRound className="size-3.5" />{selected.id === "role-super" ? permissions.length : selected.permissionKeys.length} permissions</span></div></div><div className="relative w-full sm:w-72"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search permissions" className="h-10 w-full rounded-xl border border-border pl-9 pr-3 text-xs outline-none focus:border-primary focus:ring-4 focus:ring-primary/10" /></div></div></div>
        {selected.id === "role-super" && <div className="m-5 rounded-xl border border-primary/20 bg-primary/10 p-4 text-xs leading-5 text-muted-foreground"><strong className="text-primary">Super Admin is unrestricted.</strong> The checked permissions below visualize coverage only; they are not individually assigned and cannot be modified.</div>}
        <div className="grid gap-px bg-muted lg:grid-cols-2">{grouped.map(({ group, permissions: groupPermissions }) => <div key={group} className="bg-card p-5"><div className="mb-3 flex items-center justify-between"><h3 className="text-xs font-bold uppercase tracking-[0.1em] text-muted-foreground">{group}</h3><span className="text-[10px] text-muted-foreground">{groupPermissions.filter((permission) => selected.id === "role-super" || selected.permissionKeys.includes(permission.key)).length}/{groupPermissions.length}</span></div><div className="space-y-1">{groupPermissions.map((permission) => { const enabled = selected.id === "role-super" || selected.permissionKeys.includes(permission.key); return <button disabled={selected.id === "role-super"} onClick={() => toggleRolePermission(selected.id, permission.key)} key={permission.key} className={cn("flex w-full items-start gap-3 rounded-xl p-3 text-left transition", selected.id !== "role-super" && "hover:bg-muted/40")}><span className={cn("mt-0.5 grid size-5 shrink-0 place-items-center rounded-md border", enabled ? "border-emerald-500 bg-emerald-500/100 text-primary-foreground" : "border-border text-transparent")}><Check className="size-3" /></span><span className="min-w-0 flex-1"><span className="block text-xs font-semibold text-foreground">{permission.label}</span><code className="mt-1 block text-[9px] text-muted-foreground">{permission.key}</code></span>{enabled ? <Check className="mt-1 size-3.5 text-emerald-500" /> : <X className="mt-1 size-3.5 text-muted-foreground/60" />}</button>; })}</div></div>)}</div>
      </section>
    </div>
  </div>;
}


