"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
import { Eye, EyeOff, LockKeyhole, Mail } from "lucide-react";
import AuthShell from "@/components/auth/auth-shell";

export default function LoginPage() {
  const router = useRouter(); const supabase = createClient(); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [showPassword, setShowPassword] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [pending, setPending] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); setNotice(""); setPending(true); const { error } = await supabase.auth.signInWithPassword({ email: email.trim(), password }); setPending(false); if (error) return setError(error.message); router.replace("/dashboard"); router.refresh(); }
  async function resetPassword() { if (!email.trim()) return setError("Enter your email first."); const { error } = await supabase.auth.resetPasswordForEmail(email.trim(), { redirectTo: `${window.location.origin}/auth/callback?next=/reset-password` }); if (error) setError(error.message); else setNotice("Check your email for a password reset link."); }
  return <AuthShell eyebrow="Super Admin control center" title="Welcome back" description="Sign in to govern access, clients, and the PSS Logistics network."><form onSubmit={submit} className="space-y-5"><label className="block text-xs font-semibold text-[#344259]">Admin email<div className="relative mt-2"><Mail className="pointer-events-none absolute left-3.5 top-1/2 size-4 -translate-y-1/2 text-[#94a3b8]"/><input required type="email" autoComplete="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="admin@psslogistics.in" className="h-12 w-full rounded-xl border border-[#dbe5f2] bg-[#f8fafc] pl-10 pr-3 text-sm outline-none focus:border-[#2563eb] focus:bg-white focus:ring-4 focus:ring-[#2563eb]/10"/></div></label><label className="block text-xs font-semibold text-[#344259]">Password<div className="relative mt-2"><LockKeyhole className="pointer-events-none absolute left-3.5 top-1/2 size-4 -translate-y-1/2 text-[#94a3b8]"/><input required type={showPassword ? "text" : "password"} autoComplete="current-password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Enter your password" className="h-12 w-full rounded-xl border border-[#dbe5f2] bg-[#f8fafc] pl-10 pr-11 text-sm outline-none focus:border-[#2563eb] focus:bg-white focus:ring-4 focus:ring-[#2563eb]/10"/><button type="button" onClick={() => setShowPassword((value) => !value)} aria-label={showPassword ? "Hide password" : "Show password"} className="absolute right-3 top-1/2 -translate-y-1/2 p-1 text-[#94a3b8]">{showPassword ? <EyeOff className="size-4"/> : <Eye className="size-4"/>}</button></div></label>{error && <p role="alert" className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}{notice && <p role="status" className="rounded-xl border border-blue-200 bg-blue-50 p-3 text-sm text-blue-700">{notice}</p>}<button disabled={pending} className="h-12 w-full rounded-xl bg-[#2563eb] text-sm font-semibold text-white shadow-lg shadow-[#2563eb]/20 hover:bg-[#1d4ed8] disabled:opacity-60">{pending ? "Signing in…" : "Sign in to control center"}</button><button type="button" onClick={resetPassword} className="mx-auto block text-xs font-semibold text-[#2563eb] hover:underline">Forgot password?</button></form></AuthShell>;
}
