"use client";

import { createContext, useContext, useMemo, useState } from "react";
import {
  Activity, AlertTriangle, ArrowDownToLine, ArrowRight, Boxes, BookOpenCheck, Check,
  ChevronRight, CircleAlert, Clock3, ContactRound, FileCheck2, Filter, Gauge,
  ListChecks, LockKeyhole, PackageCheck, PackageSearch, Plus, RotateCcw, Search,
  Send, Settings2, Truck, UserRound,
  Users, Workflow, XCircle,
} from "lucide-react";
import { Modal, StatusBadge, inputClass } from "@/components/admin/ui";
import type { AdminNavItem } from "@/lib/admin-navigation";
import { cn } from "@/lib/utils";

type Tone = "neutral" | "positive" | "warning" | "critical" | "navy";
type WorkspaceAction = { label: string; entity?: string };
type WorkspaceActionContextValue = { openAction(label: string, entity?: string): void };

const WorkspaceActionContext = createContext<WorkspaceActionContextValue | null>(null);

function useWorkspaceAction() {
  const context = useContext(WorkspaceActionContext);
  if (!context) throw new Error("Workspace actions must be used inside a module workspace");
  return context;
}

const routeCopy: Record<string, { eyebrow: string; intro: string; primary: string; kind: string }> = {
  "/alerts-attention": { eyebrow: "Attention queue", intro: "Prioritize operational risk, ownership gaps, and decisions waiting on the Super Admin.", primary: "Create alert rule", kind: "queue" },
  "/operations/shipments": { eyebrow: "Shipment register", intro: "Search every client shipment and move quickly from exception to accountable owner.", primary: "Export register", kind: "register" },
  "/operations/bookings": { eyebrow: "Booking desk", intro: "Create and supervise single or bulk bookings with documents and courier context in view.", primary: "New booking", kind: "form" },
  "/operations/tracking": { eyebrow: "Movement control", intro: "Follow milestones, identify stalled movement, and record the next operational action.", primary: "Track shipment", kind: "timeline" },
  "/operations/pickups": { eyebrow: "Pickup control", intro: "Coordinate scheduled collections, capacity, driver ownership, and failed pickup recovery.", primary: "Schedule pickup", kind: "schedule" },
  "/operations/returns": { eyebrow: "RTO desk", intro: "Review automatic return movement and complete the documents required for the next leg.", primary: "Review documents", kind: "documents" },
  "/operations/exceptions": { eyebrow: "Exception desk", intro: "Triage holds, delays, and failed services with an owner and resolution deadline.", primary: "Assign exception", kind: "queue" },
  "/clients": { eyebrow: "Client directory", intro: "See account health, operational volume, ownership, and the next client decision.", primary: "Add client", kind: "directory" },
  "/clients/onboarding": { eyebrow: "Verification queue", intro: "Review business identity, KYC documents, and the decision required to activate an account.", primary: "Start onboarding", kind: "verification" },
  "/clients/activity": { eyebrow: "Client timeline", intro: "Trace shipment, support, ownership, and administrative activity by client.", primary: "Export activity", kind: "timeline" },
  "/departments": { eyebrow: "Organization map", intro: "Understand functional ownership, manager coverage, and available team capacity.", primary: "Create department", kind: "organization" },
  "/tasks": { eyebrow: "Work queue", intro: "Monitor overdue work and move operational tasks to the employee best placed to complete them.", primary: "Create task", kind: "tasks" },
  "/employee-activity": { eyebrow: "Activity ledger", intro: "Review employee actions with actor, entity, timestamp, and security context.", primary: "Export ledger", kind: "timeline" },
  "/support/tickets": { eyebrow: "Support inbox", intro: "Resolve client conversations with shipment context, ownership, and SLA visibility.", primary: "New ticket", kind: "inbox" },
  "/support/sla-escalations": { eyebrow: "SLA monitor", intro: "Focus the team on due-soon and breached support commitments before they become escalations.", primary: "Configure SLA", kind: "monitor" },
  "/finance/wallets": { eyebrow: "Wallet control", intro: "Review client balances, holds, and adjustments before changing available credit.", primary: "Record adjustment", kind: "ledger" },
  "/finance/billing-invoices": { eyebrow: "Invoice desk", intro: "Manage invoice status, billing exceptions, and approval exposure in one register.", primary: "Create invoice", kind: "ledger" },
  "/finance/transactions": { eyebrow: "Transaction ledger", intro: "Reconcile wallet and billing movements with client and actor attribution.", primary: "Export ledger", kind: "ledger" },
  "/insights/analytics": { eyebrow: "Analytics studio", intro: "Compare operational trends across clients, employees, couriers, and services.", primary: "Build report", kind: "analytics" },
  "/insights/reports": { eyebrow: "Report catalogue", intro: "Generate governed reports, schedule recurring exports, and inspect download history.", primary: "Create report", kind: "reports" },
  "/insights/performance": { eyebrow: "Performance center", intro: "Compare service, client, courier, and employee performance against useful operating signals.", primary: "Compare teams", kind: "analytics" },
  "/automation/workflow-rules": { eyebrow: "Workflow builder", intro: "Define event-driven routing, assignment, and escalation rules with visible execution history.", primary: "Create rule", kind: "rules" },
  "/automation/notification-rules": { eyebrow: "Notification routing", intro: "Control which events reach which recipients, with severity and channel made explicit.", primary: "Add notification rule", kind: "rules" },
  "/automation/scheduled-jobs": { eyebrow: "Job monitor", intro: "Supervise scheduled workers, retries, and the next run of system processes.", primary: "Run job", kind: "monitor" },
  "/integrations/couriers": { eyebrow: "Courier health", intro: "Monitor carrier connectivity, latency, service configuration, and recent API failures.", primary: "Connect courier", kind: "integrations" },
  "/integrations/channels": { eyebrow: "Channel health", intro: "Manage email, WhatsApp, and SMS delivery channels and their failure states.", primary: "Add channel", kind: "integrations" },
  "/integrations/api-webhooks": { eyebrow: "Developer access", intro: "Govern API keys, webhook endpoints, scopes, and delivery attempts.", primary: "Create API key", kind: "integrations" },
  "/system/security-sessions": { eyebrow: "Security monitor", intro: "Review active sessions, authentication risk, and access that needs revocation.", primary: "Revoke session", kind: "security" },
  "/system/notifications": { eyebrow: "Notification center", intro: "Review operational and administrative events by priority, category, and acknowledgement state.", primary: "Mark all read", kind: "inbox" },
  "/system/settings": { eyebrow: "Platform controls", intro: "Manage organization defaults and policy configuration with an explicit change boundary.", primary: "Save settings", kind: "settings" },
};

const sampleRows = [
  ["Northwind Pharma", "Shipment exception", "Owner action required", "12 min", "critical"],
  ["Arvind Components", "Pickup cutoff", "Driver assignment", "28 min", "warning"],
  ["Jaipur Craft House", "KYC document", "Review pending", "1 hr", "warning"],
  ["Orion Auto Parts", "Invoice approval", "Ready for review", "3 hr", "positive"],
] as const;

type SerializableAdminNavItem = Omit<AdminNavItem, "icon">;

const iconByRoute = {
  "/alerts-attention": AlertTriangle,
  "/operations/shipments": Boxes,
  "/operations/bookings": BookOpenCheck,
  "/operations/tracking": PackageSearch,
  "/operations/pickups": Truck,
  "/operations/returns": RotateCcw,
  "/clients/onboarding": ContactRound,
} as const;

export default function AdminModuleWorkspace({ module }: { module: SerializableAdminNavItem }) {
  const copy = routeCopy[module.href] ?? { eyebrow: "Module workspace", intro: module.description, primary: "Open workspace", kind: "settings" };
  const Icon = iconByRoute[module.href as keyof typeof iconByRoute] ?? Boxes;
  const [query, setQuery] = useState("");
  const [notice, setNotice] = useState<string | null>(null);
  const [filter, setFilter] = useState("All");
  const [action, setAction] = useState<WorkspaceAction | null>(null);
  const [actionNote, setActionNote] = useState("");
  const [actionHistory, setActionHistory] = useState<string[]>([]);
  const rows = useMemo(() => sampleRows.filter((row) => `${row[0]} ${row[1]} ${row[2]}`.toLowerCase().includes(query.toLowerCase()) && (filter === "All" || row[4] === filter)), [filter, query]);

  function runPrimary() {
    if (/export/i.test(copy.primary)) {
      const csv = ["Entity,Issue,Next action,Age,Severity", ...sampleRows.map((row) => row.join(","))].join("\n");
      const link = document.createElement("a"); link.href = `data:text/csv;charset=utf-8,${encodeURIComponent(csv)}`; link.download = `${module.href.slice(1).replaceAll("/", "-")}-export.csv`; link.click();
      setNotice(`${copy.primary} downloaded with ${sampleRows.length} records.`);
      return;
    }
    openAction(copy.primary, module.label);
  }

  function openAction(label: string, entity?: string) { setAction({ label, entity }); setActionNote(""); }
  function submitAction() {
    if (!action) return;
    const result = `${action.label}${action.entity ? ` · ${action.entity}` : ""}`;
    setActionHistory((current) => [result, ...current].slice(0, 5));
    setAction(null); setActionNote(""); setNotice(`${result} recorded with an integration-ready action payload.`);
  }

  return <WorkspaceActionContext.Provider value={{ openAction }}><div className="w-full space-y-5">
    <header className="flex flex-col gap-4 border-b border-border/70 pb-5 xl:flex-row xl:items-end xl:justify-between">
      <div className="flex items-start gap-3"><div className="grid size-10 shrink-0 place-items-center rounded-xl bg-primary/10 text-primary"><Icon className="size-[18px]" /></div><div><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-primary">{copy.eyebrow}</p><h1 className="mt-1 text-2xl font-semibold tracking-[-0.035em]">{module.label}</h1><p className="mt-1 max-w-3xl text-xs leading-5 text-muted-foreground">{copy.intro}</p></div></div>
      <div className="flex flex-wrap items-center gap-2"><StatusBadge tone={module.status === "planned" ? "warning" : "positive"}>{module.status === "planned" ? "Workflow planned" : "Prototype workspace"}</StatusBadge><button onClick={runPrimary} className="inline-flex h-9 items-center gap-2 rounded-lg bg-primary px-3 text-xs font-semibold text-primary-foreground shadow-sm hover:bg-primary/90"><Plus className="size-3.5" />{copy.primary}</button></div>
    </header>
    {notice && <button onClick={() => setNotice(null)} className="flex w-full items-center justify-between rounded-lg border border-primary/20 bg-primary/5 px-3 py-2 text-left text-xs text-primary"><span>{notice}</span><XCircle className="size-4" /></button>}
    {copy.kind === "form" && <BookingWorkspace />}
    {copy.kind === "register" && <RegisterWorkspace query={query} setQuery={setQuery} rows={rows} />}
    {copy.kind === "timeline" && <TimelineWorkspace query={query} setQuery={setQuery} />}
    {copy.kind === "documents" && <DocumentsWorkspace />}
    {copy.kind === "verification" && <VerificationWorkspace />}
    {copy.kind === "schedule" && <ScheduleWorkspace />}
    {copy.kind === "directory" && <DirectoryWorkspace query={query} setQuery={setQuery} />}
    {copy.kind === "organization" && <OrganizationWorkspace />}
    {copy.kind === "tasks" && <TasksWorkspace />}
    {copy.kind === "inbox" && <InboxWorkspace query={query} setQuery={setQuery} filter={filter} setFilter={setFilter} rows={rows} />}
    {copy.kind === "ledger" && <LedgerWorkspace query={query} setQuery={setQuery} />}
    {copy.kind === "analytics" && <AnalyticsWorkspace />}
    {copy.kind === "reports" && <ReportsWorkspace />}
    {copy.kind === "rules" && <RulesWorkspace />}
    {copy.kind === "monitor" && <MonitorWorkspace />}
    {copy.kind === "integrations" && <IntegrationsWorkspace />}
    {copy.kind === "security" && <SecurityWorkspace />}
    {(copy.kind === "queue" || copy.kind === "settings") && <QueueOrSettingsWorkspace kind={copy.kind} query={query} setQuery={setQuery} filter={filter} setFilter={setFilter} rows={rows} />}
    {actionHistory.length > 0 && <div className="rounded-xl border border-border bg-card px-4 py-3 shadow-xs"><div className="flex items-center justify-between"><p className="text-xs font-semibold">Recent actions</p><span className="text-[10px] text-muted-foreground">Local audit queue</span></div><div className="mt-2 flex flex-wrap gap-2">{actionHistory.map((item) => <StatusBadge key={item} tone="positive">{item}</StatusBadge>)}</div></div>}
    <ActionDialog action={action} note={actionNote} setNote={setActionNote} onClose={() => setAction(null)} onSubmit={submitAction} />
  </div></WorkspaceActionContext.Provider>;
}

function WorkspaceCard({ title, detail, children, className }: { title: string; detail?: string; children: React.ReactNode; className?: string }) { return <section className={cn("overflow-hidden rounded-xl border border-border bg-card shadow-xs", className)}><div className="flex items-center justify-between border-b border-border/70 px-4 py-3"><div><h2 className="text-sm font-semibold">{title}</h2>{detail && <p className="mt-1 text-[11px] text-muted-foreground">{detail}</p>}</div></div>{children}</section>; }
function Toolbar({ query, setQuery, filter, setFilter, placeholder = "Search workspace" }: { query: string; setQuery(v: string): void; filter?: string; setFilter?: (v: string) => void; placeholder?: string }) { const { openAction } = useWorkspaceAction(); return <div className="flex flex-col gap-2 border-b border-border/70 p-3 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 size-3.5 -translate-y-1/2 text-muted-foreground" /><input value={query} onChange={(e) => setQuery(e.target.value)} className={cn(inputClass, "h-9 pl-9 text-xs")} placeholder={placeholder} /></div>{setFilter && <div className="flex gap-1 rounded-lg bg-muted p-1">{["All", "critical", "warning", "positive"].map((item) => <button key={item} onClick={() => setFilter(item)} className={cn("rounded-md px-2.5 py-1 text-[10px] font-semibold capitalize", filter === item ? "bg-card text-foreground shadow-xs" : "text-muted-foreground")}>{item}</button>)}</div>}<button onClick={() => openAction("Open advanced filters")} className="inline-flex h-9 items-center justify-center gap-1.5 rounded-lg border border-border px-3 text-xs font-semibold text-muted-foreground hover:bg-muted"><Filter className="size-3.5" />Filter</button></div>; }
function MetricStrip({ items }: { items: [string, string, Tone][] }) { return <div className="grid border-b border-border/70 sm:grid-cols-3">{items.map(([label, value, tone], i) => <div key={label} className={cn("px-4 py-3", i > 0 && "border-t border-border/70 sm:border-l sm:border-t-0")}><p className={cn("text-xl font-bold tabular-nums", tone === "critical" ? "text-destructive" : tone === "warning" ? "text-amber-600" : tone === "positive" ? "text-emerald-600" : "text-foreground")}>{value}</p><p className="mt-0.5 text-[10px] text-muted-foreground">{label}</p></div>)}</div>; }
function Row({ item }: { item: readonly [string, string, string, string, string] }) { const { openAction } = useWorkspaceAction(); return <button onClick={() => openAction(`Inspect ${item[1]}`, item[0])} className="grid w-full grid-cols-[10px_minmax(150px,1.2fr)_minmax(140px,1fr)_72px_22px] items-center gap-3 px-4 py-3 text-left transition-colors hover:bg-muted/50"><span className={cn("size-2 rounded-full", item[4] === "critical" ? "bg-destructive" : item[4] === "warning" ? "bg-amber-500" : "bg-emerald-500")} /><span className="min-w-0"><span className="block truncate text-xs font-semibold">{item[0]}</span><span className="block truncate text-[10px] text-muted-foreground">{item[1]}</span></span><span className="truncate text-[11px] text-muted-foreground">{item[2]}</span><span className="text-[10px] font-semibold text-muted-foreground">{item[3]}</span><ChevronRight className="size-3.5 text-muted-foreground" /></button>; }

function RegisterWorkspace({ query, setQuery, rows }: { query: string; setQuery(v: string): void; rows: typeof sampleRows[number][] }) { return <div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_320px]"><WorkspaceCard title="Shipment register" detail="Global scope · 2,481 shipments · updated just now"><MetricStrip items={[["In transit", "1,204", "navy"], ["Delivered today", "486", "positive"], ["Exceptions", "37", "critical"]]} /><Toolbar query={query} setQuery={setQuery} placeholder="Search AWB, client, courier, or city" /><div className="hidden grid-cols-[1.2fr_1fr_1fr_110px] gap-3 border-b border-border/70 bg-muted/40 px-4 py-2 text-[10px] font-bold uppercase tracking-wider text-muted-foreground"><span>Shipment / client</span><span>Movement</span><span>Courier</span><span>Status</span></div>{rows.map((row) => <Row item={row} key={row[0]} />)}</WorkspaceCard><WorkspaceCard title="Selected shipment" detail="Choose a row to inspect movement and ownership"><div className="space-y-4 p-4"><div className="rounded-lg bg-muted/40 p-3"><p className="font-mono text-xs font-bold">PSS-2026-004821</p><p className="mt-1 text-[11px] text-muted-foreground">Northwind Pharma · Mumbai → Delhi</p></div><DetailLine label="Current milestone" value="Out for delivery" /><DetailLine label="Accountable owner" value="Rahul Sharma" /><DetailLine label="Next action" value="Confirm delivery attempt" /></div></WorkspaceCard></div>; }

function BookingWorkspace() { const { openAction } = useWorkspaceAction(); return <div className="grid gap-4 xl:grid-cols-[minmax(0,1.4fr)_360px]"><WorkspaceCard title="Create booking" detail="Select a flow, then complete the minimum shipment information"><div className="grid gap-3 border-b border-border/70 p-4 sm:grid-cols-2"><Choice active title="Single booking" detail="One shipment with guided validation" icon={PackageCheck} /><Choice title="Bulk upload" detail="CSV/XLSX with row-level review" icon={Boxes} /></div><div className="grid gap-4 p-4 sm:grid-cols-2"><FieldBox label="Consignor" value="Select client or saved address" /><FieldBox label="Consignee" value="Add delivery party" /><FieldBox label="Pickup location" value="Mumbai warehouse" /><FieldBox label="Service level" value="Express · 1–2 days" /></div><div className="flex justify-end border-t border-border/70 p-3"><button onClick={() => openAction("Continue to documents", "New shipment booking")} className="inline-flex h-9 items-center gap-2 rounded-lg bg-primary px-3 text-xs font-semibold text-primary-foreground"><ArrowRight className="size-3.5" />Continue to documents</button></div></WorkspaceCard><WorkspaceCard title="Booking readiness" detail="Required before label generation"><div className="divide-y divide-border/70"><CheckRow label="Party details" value="Not started" /><CheckRow label="Package dimensions" value="Not started" /><CheckRow label="Invoice / challan" value="Required" warning /><CheckRow label="Courier selection" value="After validation" /></div></WorkspaceCard></div>; }
function TimelineWorkspace({ query, setQuery }: { query: string; setQuery(v: string): void }) { const { openAction } = useWorkspaceAction(); return <div className="grid gap-4 xl:grid-cols-[320px_minmax(0,1fr)]"><WorkspaceCard title="Activity stream" detail="Newest events across this module"><Toolbar query={query} setQuery={setQuery} placeholder="Search entity or actor" /><div className="divide-y divide-border/70">{["Shipment PSS-2026-004821 delivered", "Client responsibility transferred", "Pickup attempt marked failed", "Support ticket escalated"].map((item, i) => <button key={item} onClick={() => openAction("Inspect activity event", item)} className="flex w-full items-start gap-3 px-4 py-3 text-left hover:bg-muted/50"><span className={cn("mt-1.5 size-2 shrink-0 rounded-full", i === 2 ? "bg-amber-500" : "bg-primary")} /><span className="min-w-0 flex-1"><span className="block text-xs font-semibold">{item}</span><span className="mt-1 block text-[10px] text-muted-foreground">{["2 min ago", "18 min ago", "42 min ago", "1 hr ago"][i]} · System event</span></span><ChevronRight className="mt-1 size-3.5 text-muted-foreground" /></button>)}</div></WorkspaceCard><WorkspaceCard title="Event detail" detail="Select an event to inspect the before and after state"><div className="p-4"><div className="flex items-center gap-2"><Activity className="size-4 text-primary" /><p className="text-sm font-semibold">Shipment delivered</p><StatusBadge tone="positive">Completed</StatusBadge></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><DetailLine label="Entity" value="PSS-2026-004821" /><DetailLine label="Actor" value="Courier webhook" /><DetailLine label="Previous state" value="Out for delivery" /><DetailLine label="New state" value="Delivered" /></div><div className="mt-4 rounded-lg border border-border bg-muted/30 p-3 text-[11px] leading-5 text-muted-foreground">Timeline events remain locally simulated until the production event stream is connected.</div></div></WorkspaceCard></div>; }
function DocumentsWorkspace() { const { openAction } = useWorkspaceAction(); return <div className="grid gap-4 lg:grid-cols-[1fr_360px]"><WorkspaceCard title="Documentation queue" detail="RTO movements waiting for an operator decision"><MetricStrip items={[["Documents pending", "12", "warning"], ["Ready for return", "28", "positive"], ["Blocked", "4", "critical"]]} /><div className="divide-y divide-border/70">{["RTO-004821 · Northwind Pharma", "RTO-004799 · Arvind Components", "RTO-004766 · Jaipur Craft House"].map((item, i) => <button key={item} onClick={() => openAction("Open document pack", item)} className="flex w-full items-center gap-3 px-4 py-3 text-left hover:bg-muted/50"><FileCheck2 className={cn("size-4", i === 0 ? "text-amber-500" : "text-emerald-500")} /><span className="min-w-0 flex-1"><span className="block truncate text-xs font-semibold">{item}</span><span className="block text-[10px] text-muted-foreground">{i === 0 ? "Invoice and delivery challan required" : "Document pack complete"}</span></span><StatusBadge tone={i === 0 ? "warning" : "positive"}>{i === 0 ? "Pending" : "Ready"}</StatusBadge></button>)}</div></WorkspaceCard><WorkspaceCard title="Document pack" detail="RTO-004821 · selected return"><div className="divide-y divide-border/70"><CheckRow label="Original invoice" value="Missing" warning /><CheckRow label="Delivery challan" value="Uploaded" /><CheckRow label="E-Way Bill" value="Not required" /><CheckRow label="Return movement" value="Automatic" /></div></WorkspaceCard></div>; }
function VerificationWorkspace() { const { openAction } = useWorkspaceAction(); return <div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_340px]"><WorkspaceCard title="Verification queue" detail="New accounts sorted by risk and document completeness"><div className="flex flex-wrap gap-2 border-b border-border/70 p-3"><StatusBadge tone="warning">8 awaiting review</StatusBadge><StatusBadge tone="critical">2 missing PAN</StatusBadge><StatusBadge tone="positive">14 approved this month</StatusBadge></div><div className="divide-y divide-border/70">{["Northwind Pharma", "Jaipur Craft House", "Orion Auto Parts", "Arvind Components"].map((name, i) => <button key={name} onClick={() => openAction("Review KYC application", name)} className="flex w-full items-center gap-3 px-4 py-3 text-left hover:bg-muted/50"><div className="grid size-8 place-items-center rounded-lg bg-primary/10 text-primary"><UserRound className="size-4" /></div><span className="min-w-0 flex-1"><span className="block text-xs font-semibold">{name}</span><span className="block text-[10px] text-muted-foreground">GSTIN {i === 1 ? "missing" : "submitted"} · {i + 1} documents pending</span></span><StatusBadge tone={i === 1 ? "critical" : "warning"}>{i === 1 ? "Needs info" : "Review"}</StatusBadge></button>)}</div></WorkspaceCard><WorkspaceCard title="Review checklist" detail="Make a decision only after the evidence is complete"><div className="space-y-3 p-4"><CheckRow label="Business information" value="Submitted" /><CheckRow label="GSTIN / PAN match" value="Needs review" warning /><CheckRow label="Identity documents" value="3 of 4 received" warning /><button onClick={() => openAction("Open review workspace", "KYC queue")} className="mt-2 h-9 w-full rounded-lg bg-primary text-xs font-semibold text-primary-foreground">Open review workspace</button></div></WorkspaceCard></div>; }
function ScheduleWorkspace() { const { openAction } = useWorkspaceAction(); return <div className="grid gap-4 lg:grid-cols-[1fr_360px]"><WorkspaceCard title="Pickup schedule" detail="Today · Mumbai, Delhi, Bengaluru"><MetricStrip items={[["Scheduled", "46", "positive"], ["Unassigned", "7", "warning"], ["Failed", "3", "critical"]]} /><div className="grid gap-3 p-4 sm:grid-cols-3">{["08:00–10:00", "10:00–13:00", "13:00–16:00"].map((slot, i) => <button key={slot} onClick={() => openAction("Reserve pickup capacity", slot)} className="rounded-xl border border-border p-3 text-left hover:border-primary/40 hover:bg-primary/5"><p className="text-xs font-semibold">{slot}</p><p className="mt-2 text-2xl font-bold">{[12, 24, 10][i]}</p><p className="text-[10px] text-muted-foreground">{i === 1 ? "2 slots left" : "capacity available"}</p></button>)}</div><div className="divide-y divide-border/70">{["Northwind Pharma · Andheri", "Arvind Components · Bhiwandi", "Jaipur Craft House · Mansarovar"].map((item, i) => <div key={item} className="flex items-center gap-3 px-4 py-3"><Truck className="size-4 text-primary" /><span className="flex-1 text-xs font-semibold">{item}<span className="mt-1 block text-[10px] font-normal text-muted-foreground">{i === 1 ? "Unassigned · cutoff in 28 min" : "Driver assigned · 10:00–13:00"}</span></span><button onClick={() => openAction(i === 1 ? "Assign pickup driver" : "Open pickup detail", item)}><StatusBadge tone={i === 1 ? "warning" : "positive"}>{i === 1 ? "Assign" : "Scheduled"}</StatusBadge></button></div>)}</div></WorkspaceCard><WorkspaceCard title="Standalone request" detail="Schedule pickup even without an existing booking"><div className="space-y-3 p-4"><FieldBox label="Client / location" value="Choose pickup location" /><FieldBox label="Preferred slot" value="Tomorrow · 10:00–13:00" /><button onClick={() => openAction("Create pickup request", "Standalone request")} className="h-9 w-full rounded-lg bg-primary text-xs font-semibold text-primary-foreground">Create pickup request</button></div></WorkspaceCard></div>; }
function DirectoryWorkspace({ query, setQuery }: { query: string; setQuery(v: string): void }) { return <WorkspaceCard title="Client directory" detail="Account health and operational ownership"><Toolbar query={query} setQuery={setQuery} placeholder="Search client, code, city, or owner" /><div className="divide-y divide-border/70">{["Northwind Pharma", "Arvind Components", "Jaipur Craft House", "Orion Auto Parts"].filter((item) => item.toLowerCase().includes(query.toLowerCase())).map((name, i) => <div key={name} className="grid gap-2 px-4 py-3 sm:grid-cols-[1.4fr_1fr_130px_110px] sm:items-center"><span><span className="block text-xs font-semibold">{name}</span><span className="text-[10px] text-muted-foreground">CL-00{i + 18} · {['Mumbai', 'Delhi', 'Jaipur', 'Pune'][i]}</span></span><span className="text-[11px] text-muted-foreground">{['Rahul Sharma', 'Priya Mehta', 'Unassigned', 'Amit Shah'][i]}</span><span className="text-[11px] font-semibold">{[211, 84, 36, 159][i]} shipments</span><StatusBadge tone={i === 2 ? "warning" : "positive"}>{i === 2 ? "At risk" : "Healthy"}</StatusBadge></div>)}</div></WorkspaceCard>; }
function OrganizationWorkspace() { return <div className="grid gap-4 lg:grid-cols-[1fr_360px]"><WorkspaceCard title="Department capacity" detail="Ownership and manager coverage"><div className="divide-y divide-border/70">{["Operations", "Client Success", "Finance", "Technology"].map((name, i) => <div key={name} className="flex items-center gap-3 px-4 py-4"><div className="grid size-9 place-items-center rounded-lg bg-primary/10 text-primary"><Users className="size-4" /></div><span className="min-w-0 flex-1"><span className="block text-xs font-semibold">{name}</span><span className="mt-1 block text-[10px] text-muted-foreground">{[18, 7, 4, 3][i]} members · manager {['Amit Shah', 'Priya Mehta', 'Neha Rao', 'Rahul Sharma'][i]}</span></span><span className="text-xs font-bold">{[78, 62, 46, 71][i]}%</span></div>)}</div></WorkspaceCard><WorkspaceCard title="Coverage gaps" detail="Decisions for the organization owner"><div className="space-y-3 p-4"><CheckRow label="Every client has an owner" value="92%" warning /><CheckRow label="Managers have active deputies" value="3 gaps" warning /><CheckRow label="Disabled identities reviewed" value="Complete" /></div></WorkspaceCard></div>; }
function TasksWorkspace() { const { openAction } = useWorkspaceAction(); return <div className="grid gap-4 md:grid-cols-3">{[["Overdue", "4", "critical"], ["Due today", "12", "warning"], ["In progress", "28", "positive"]].map(([title, count, tone]) => <WorkspaceCard key={title} title={title} detail={`${count} tasks in this view`}><div className="divide-y divide-border/70">{["Review failed pickup", "Approve client transfer", "Resolve SLA breach"].slice(0, title === "Overdue" ? 2 : 3).map((task) => <button key={task} onClick={() => openAction("Open task", task)} className="flex w-full items-center gap-2 px-4 py-3 text-left hover:bg-muted/50"><ListChecks className={cn("size-4", tone === "critical" ? "text-destructive" : tone === "warning" ? "text-amber-500" : "text-emerald-500")} /><span className="flex-1 text-xs font-semibold">{task}</span><ChevronRight className="size-3 text-muted-foreground" /></button>)}</div></WorkspaceCard>)}</div>; }
function InboxWorkspace({ query, setQuery, filter, setFilter, rows }: { query: string; setQuery(v: string): void; filter: string; setFilter(v: string): void; rows: typeof sampleRows[number][] }) { const { openAction } = useWorkspaceAction(); return <div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_340px]"><WorkspaceCard title="Priority inbox" detail="Messages and events requiring an operator response"><Toolbar query={query} setQuery={setQuery} filter={filter} setFilter={setFilter} placeholder="Search ticket, client, or shipment" />{rows.map((row) => <Row key={row[0]} item={row} />)}</WorkspaceCard><WorkspaceCard title="Conversation context" detail="Select a message to open the full thread"><div className="p-4"><div className="rounded-lg bg-muted/40 p-3"><p className="text-xs font-semibold">Northwind Pharma</p><p className="mt-1 text-[10px] text-muted-foreground">Shipment PSS-2026-004821 · Priority support</p></div><div className="mt-4 space-y-3"><p className="rounded-lg bg-muted p-3 text-[11px] leading-5">“The delivery attempt is still not visible in our portal.”</p><p className="ml-8 rounded-lg bg-primary/10 p-3 text-[11px] leading-5">Assigned to Rahul Sharma. Response due in 18 minutes.</p></div><button onClick={() => openAction("Reply to support thread", "PSS-2026-004821")} className="mt-4 flex h-9 w-full items-center justify-center gap-2 rounded-lg border border-border text-xs font-semibold hover:bg-muted"><Send className="size-3.5" />Reply to thread</button></div></WorkspaceCard></div>; }
function LedgerWorkspace({ query, setQuery }: { query: string; setQuery(v: string): void }) { return <WorkspaceCard title="Financial register" detail="Provider-neutral ledger · local prototype"><MetricStrip items={[["Pending approval", "₹2.4L", "warning"], ["Available balance", "₹18.7L", "positive"], ["On hold", "₹84K", "critical"]]} /><Toolbar query={query} setQuery={setQuery} placeholder="Search client, invoice, transaction, or actor" /><div className="divide-y divide-border/70">{["Northwind Pharma · INV-2048", "Arvind Components · TXN-9921", "Jaipur Craft House · WAL-0182", "Orion Auto Parts · INV-2031"].map((item, i) => <div key={item} className="grid gap-2 px-4 py-3 sm:grid-cols-[1.4fr_1fr_120px_100px] sm:items-center"><span className="text-xs font-semibold">{item}<span className="mt-1 block text-[10px] font-normal text-muted-foreground">{['Invoice awaiting approval', 'Wallet debit · reconciled', 'Credit hold applied', 'Invoice paid'][i]}</span></span><span className="text-[11px] text-muted-foreground">{['Today, 10:42', 'Yesterday', 'Aug 10', 'Aug 08'][i]}</span><span className="text-xs font-semibold tabular-nums">{['₹42,800', '₹18,450', '₹12,000', '₹31,200'][i]}</span><StatusBadge tone={i === 0 || i === 2 ? "warning" : "positive"}>{i === 0 ? "Review" : i === 2 ? "On hold" : "Settled"}</StatusBadge></div>)}</div></WorkspaceCard>; }
function AnalyticsWorkspace() { return <div className="grid gap-4 xl:grid-cols-[1.4fr_1fr]"><WorkspaceCard title="Operating trend" detail="Last 30 days · shipments, SLA, and exceptions"><div className="p-4"><div className="flex h-48 items-end gap-2 border-b border-l border-border p-3">{[42, 58, 51, 72, 66, 84, 76, 92, 81, 96, 88, 100].map((height, i) => <div key={i} className="group flex flex-1 items-end justify-center"><div className="w-full rounded-t bg-primary/70 transition-all group-hover:bg-primary" style={{ height: `${height}%` }} /></div>)}</div><div className="mt-3 flex justify-between text-[10px] text-muted-foreground"><span>Jul 14</span><span>Jul 29</span><span>Aug 12</span></div></div></WorkspaceCard><WorkspaceCard title="Performance mix" detail="Current operating distribution"><div className="space-y-4 p-4"><Progress label="On-time delivery" value="94.8%" width={95} tone="positive" /><Progress label="First-attempt success" value="82.1%" width={82} /><Progress label="Exception closure" value="76.4%" width={76} tone="warning" /><Progress label="SLA compliance" value="91.2%" width={91} tone="positive" /></div></WorkspaceCard></div>; }
function ReportsWorkspace() { const { openAction } = useWorkspaceAction(); return <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{["Daily operations", "Client health", "Courier SLA", "Finance reconciliation", "Employee activity", "Exception ageing"].map((name, i) => <WorkspaceCard key={name} title={name} detail={`${['Scheduled daily', 'On demand', 'Weekly Monday', 'Monthly', 'On demand', 'Daily'][i]} · last run {i + 1}h ago`}><div className="flex items-center justify-between p-4"><StatusBadge tone={i === 4 ? "warning" : "positive"}>{i === 4 ? "Needs review" : "Ready"}</StatusBadge><button onClick={() => openAction("Export report", name)} className="inline-flex items-center gap-1 text-[11px] font-semibold text-primary"><ArrowDownToLine className="size-3.5" />Export</button></div></WorkspaceCard>)}</div>; }
function RulesWorkspace() { return <WorkspaceCard title="Rules catalogue" detail="Event → condition → action"><div className="divide-y divide-border/70">{[["Shipment delayed", "If milestone exceeds SLA", "Notify owner + escalate"], ["New client submitted", "If KYC is complete", "Assign Client Success"], ["Pickup failed", "If second attempt fails", "Create exception task"], ["Invoice overdue", "If due date passes", "Notify account owner"]].map(([name, condition, action], i) => <div key={name} className="grid gap-3 px-4 py-4 sm:grid-cols-[1.1fr_1.2fr_1.2fr_80px] sm:items-center"><div className="flex items-center gap-2"><Workflow className="size-4 text-primary" /><span className="text-xs font-semibold">{name}</span></div><span className="text-[11px] text-muted-foreground">{condition}</span><span className="text-[11px] font-semibold">{action}</span><StatusBadge tone={i === 2 ? "warning" : "positive"}>{i === 2 ? "Paused" : "Active"}</StatusBadge></div>)}</div></WorkspaceCard>; }
function MonitorWorkspace() { const { openAction } = useWorkspaceAction(); return <div className="grid gap-4 lg:grid-cols-[1fr_360px]"><WorkspaceCard title="Run health" detail="Workers and commitments that need attention"><MetricStrip items={[["Healthy", "18", "positive"], ["Due soon", "4", "warning"], ["Failed", "1", "critical"]]} /><div className="divide-y divide-border/70">{["SLA escalation worker", "Daily operations report", "Courier sync · Delhivery", "Notification digest"].map((job, i) => <div key={job} className="flex items-center gap-3 px-4 py-3"><div className={cn("grid size-8 place-items-center rounded-lg", i === 2 ? "bg-amber-500/10 text-amber-600" : "bg-emerald-500/10 text-emerald-600")}><Clock3 className="size-4" /></div><span className="flex-1"><span className="block text-xs font-semibold">{job}</span><span className="mt-1 block text-[10px] text-muted-foreground">{i === 2 ? "Last run failed · retry available" : `Next run in ${i + 1}h 20m`}</span></span><button onClick={() => openAction(i === 2 ? "Retry job" : "Inspect job", job)}><StatusBadge tone={i === 2 ? "warning" : "positive"}>{i === 2 ? "Retry" : "Healthy"}</StatusBadge></button></div>)}</div></WorkspaceCard><WorkspaceCard title="Execution detail" detail="Recent run history"><div className="space-y-3 p-4"><DetailLine label="Last successful run" value="Today, 09:20" /><DetailLine label="Average duration" value="1m 42s" /><DetailLine label="Retry policy" value="3 attempts" /><button onClick={() => openAction("View run history", "Scheduled jobs")} className="mt-2 h-9 w-full rounded-lg border border-border text-xs font-semibold hover:bg-muted">View run history</button></div></WorkspaceCard></div>; }
function IntegrationsWorkspace() { return <WorkspaceCard title="Connection health" detail="External services and delivery channels"><div className="divide-y divide-border/70">{["Delhivery API", "Blue Dart API", "Email · transactional", "WhatsApp · support", "Webhook · client events"].map((service, i) => <div key={service} className="flex items-center gap-3 px-4 py-3"><div className={cn("grid size-8 place-items-center rounded-lg", i === 1 ? "bg-amber-500/10 text-amber-600" : "bg-emerald-500/10 text-emerald-600")}><Gauge className="size-4" /></div><span className="flex-1"><span className="block text-xs font-semibold">{service}</span><span className="mt-1 block text-[10px] text-muted-foreground">{i === 1 ? "Latency elevated · 840ms" : `${i + 1} successful checks · credentials healthy`}</span></span><span className="font-mono text-[10px] text-muted-foreground">{i === 1 ? "Degraded" : "Connected"}</span><ChevronRight className="size-3.5 text-muted-foreground" /></div>)}</div></WorkspaceCard>; }
function SecurityWorkspace() { const { openAction } = useWorkspaceAction(); return <div className="grid gap-4 lg:grid-cols-[1fr_360px]"><WorkspaceCard title="Active sessions" detail="Revoke access when identity or location is unexpected"><div className="divide-y divide-border/70">{["Gaurav Sharma · Chrome / Windows", "Rahul Sharma · Edge / Windows", "Unknown device · Chrome / Linux"].map((session, i) => <div key={session} className="flex items-center gap-3 px-4 py-4"><div className={cn("grid size-8 place-items-center rounded-lg", i === 2 ? "bg-destructive/10 text-destructive" : "bg-primary/10 text-primary")}><LockKeyhole className="size-4" /></div><span className="flex-1"><span className="block text-xs font-semibold">{session}</span><span className="mt-1 block text-[10px] text-muted-foreground">{['Current session · Mumbai', 'Active 2h ago · Delhi', 'Risk signal · new location'][i]}</span></span><button onClick={() => openAction("Revoke session", session)} className="rounded-lg border border-border px-2.5 py-1.5 text-[10px] font-semibold hover:bg-muted">Revoke</button></div>)}</div></WorkspaceCard><WorkspaceCard title="Security posture" detail="Current access signals"><div className="space-y-3 p-4"><Progress label="MFA coverage" value="86%" width={86} tone="positive" /><Progress label="Privileged review" value="92%" width={92} tone="positive" /><Progress label="Unknown sessions" value="1" width={18} tone="critical" /></div></WorkspaceCard></div>; }
function QueueOrSettingsWorkspace({ kind, query, setQuery, filter, setFilter, rows }: { kind: string; query: string; setQuery(v: string): void; filter: string; setFilter(v: string): void; rows: typeof sampleRows[number][] }) { const { openAction } = useWorkspaceAction(); if (kind === "settings") return <div className="grid gap-4 lg:grid-cols-[1fr_340px]"><WorkspaceCard title="Organization defaults" detail="Changes affect future workflows only"><div className="divide-y divide-border/70">{["Default timezone", "Default shipment retention", "Require approval for wallet adjustments", "Enable operational email alerts"].map((label, i) => <div key={label} className="flex items-center gap-3 px-4 py-4"><Settings2 className="size-4 text-primary" /><span className="flex-1 text-xs font-semibold">{label}</span><span className="text-[11px] text-muted-foreground">{['Asia/Kolkata', '90 days', 'Enabled', 'Enabled'][i]}</span><ChevronRight className="size-3.5 text-muted-foreground" /></div>)}</div></WorkspaceCard><WorkspaceCard title="Change boundary" detail="Local prototype control"><div className="space-y-3 p-4"><p className="text-[11px] leading-5 text-muted-foreground">Settings are shown as local controls. Production persistence and audit enforcement are not connected yet.</p><button onClick={() => openAction("Review pending changes", "Organization defaults")} className="h-9 w-full rounded-lg bg-primary text-xs font-semibold text-primary-foreground">Review pending changes</button></div></WorkspaceCard></div>; return <div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_320px]"><WorkspaceCard title="Priority queue" detail="Sort by severity, ageing, and accountable owner"><MetricStrip items={[["Open items", "37", "critical"], ["Due within 1 hour", "9", "warning"], ["Resolved today", "24", "positive"]]} /><Toolbar query={query} setQuery={setQuery} filter={filter} setFilter={setFilter} placeholder="Search alert, entity, or owner" />{rows.map((row) => <Row key={row[0]} item={row} />)}</WorkspaceCard><WorkspaceCard title="Decision panel" detail="Select an item to see recommended action"><div className="space-y-4 p-4"><div className="rounded-lg border border-destructive/20 bg-destructive/5 p-3"><div className="flex items-center gap-2"><CircleAlert className="size-4 text-destructive" /><p className="text-xs font-semibold">Shipment exception</p></div><p className="mt-2 text-[11px] leading-5 text-muted-foreground">A shipment is waiting for an accountable owner and next action.</p></div><DetailLine label="Owner" value="Unassigned" /><DetailLine label="Age" value="42 minutes" /><button onClick={() => openAction("Assign and open detail", "Shipment exception")} className="h-9 w-full rounded-lg bg-primary text-xs font-semibold text-primary-foreground">Assign and open detail</button></div></WorkspaceCard></div>; }

function Choice({ title, detail, icon: Icon, active = false }: { title: string; detail: string; icon: typeof Boxes; active?: boolean }) { const { openAction } = useWorkspaceAction(); return <button onClick={() => openAction(`Select ${title}`, title)} className={cn("flex items-center gap-3 rounded-xl border p-3 text-left", active ? "border-primary bg-primary/5" : "border-border hover:bg-muted/40")}><div className={cn("grid size-8 place-items-center rounded-lg", active ? "bg-primary text-primary-foreground" : "bg-muted text-muted-foreground")}><Icon className="size-4" /></div><span><span className="block text-xs font-semibold">{title}</span><span className="mt-1 block text-[10px] text-muted-foreground">{detail}</span></span></button>; }
function FieldBox({ label, value }: { label: string; value: string }) { const { openAction } = useWorkspaceAction(); return <button onClick={() => openAction(`Set ${label}`, value)} className="block w-full text-left"><span className="mb-1.5 block text-[11px] font-semibold">{label}</span><span className="flex h-10 items-center justify-between rounded-lg border border-input bg-background px-3 text-xs text-muted-foreground"><span>{value}</span><ChevronRight className="size-3.5" /></span></button>; }
function CheckRow({ label, value, warning = false }: { label: string; value: string; warning?: boolean }) { return <div className="flex items-center gap-3 px-4 py-3"><span className={cn("grid size-6 place-items-center rounded-full", warning ? "bg-amber-500/10 text-amber-600" : "bg-emerald-500/10 text-emerald-600")}>{warning ? <CircleAlert className="size-3.5" /> : <Check className="size-3.5" />}</span><span className="flex-1 text-xs font-semibold">{label}</span><span className={cn("text-[10px] font-semibold", warning ? "text-amber-600" : "text-muted-foreground")}>{value}</span></div>; }
function DetailLine({ label, value }: { label: string; value: string }) { return <div className="flex items-center justify-between gap-4 border-b border-border/60 pb-2 text-[11px]"><span className="text-muted-foreground">{label}</span><span className="text-right font-semibold">{value}</span></div>; }
function Progress({ label, value, width, tone = "neutral" }: { label: string; value: string; width: number; tone?: Tone }) { return <div><div className="flex justify-between text-[11px]"><span className="font-semibold">{label}</span><span className="font-mono text-muted-foreground">{value}</span></div><div className="mt-1.5 h-1.5 overflow-hidden rounded-full bg-muted"><div className={cn("h-full rounded-full", tone === "positive" ? "bg-emerald-500" : tone === "warning" ? "bg-amber-500" : tone === "critical" ? "bg-destructive" : "bg-primary")} style={{ width: `${width}%` }} /></div></div>; }
function ActionDialog({ action, note, setNote, onClose, onSubmit }: { action: WorkspaceAction | null; note: string; setNote(value: string): void; onClose(): void; onSubmit(): void }) {
  return <Modal open={Boolean(action)} onClose={onClose} title={action?.label ?? "Workspace action"} description="Capture the operator decision and hand the structured payload to the backend integration."><div className="space-y-4"><div className="rounded-lg bg-muted/40 p-3"><p className="text-xs font-semibold">{action?.entity ?? "Selected workspace item"}</p><p className="mt-1 text-[10px] text-muted-foreground">Action: {action?.label}</p></div><label className="block"><span className="mb-1.5 block text-xs font-semibold">Operator note</span><textarea value={note} onChange={(event) => setNote(event.target.value)} className="min-h-24 w-full resize-y rounded-lg border border-input bg-background p-3 text-xs outline-none focus:border-primary focus:ring-4 focus:ring-primary/10" placeholder="State the decision, owner, deadline, or integration reference." /></label><div className="flex justify-end gap-2 border-t border-border/70 pt-4"><button type="button" onClick={onClose} className="h-9 rounded-lg border border-border px-3 text-xs font-semibold hover:bg-muted">Cancel</button><button type="button" onClick={onSubmit} className="h-9 rounded-lg bg-primary px-3 text-xs font-semibold text-primary-foreground hover:bg-primary/90">Record action</button></div></div></Modal>;
}
