"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { ArrowLeft, Ban, Building2, Check, Clock3, KeyRound, Mail, MapPin, Pencil, Phone, ShieldCheck, TicketCheck, UserRound, X } from "lucide-react";
import { useAdmin } from "@/components/admin/admin-provider";
import { EmployeeForm } from "@/components/admin/employee-form";
import { EmptyState, Modal, StatusBadge } from "@/components/admin/ui";
import { getEffectivePermissions, type EmployeeDraft, type Permission, type PermissionKey } from "@/lib/admin-domain";
import { cn } from "@/lib/utils";

const tabs = ["Overview", "Permissions", "Clients", "Activity", "Tickets", "Performance", "Security"];

export function EmployeeDetail({ employeeId }: { employeeId: string }) {
  const { employees, roles, clients, auditEvents, permissionCatalog, updateEmployee, toggleEmployeeStatus, setPermissionOverride } = useAdmin();
  const [tab, setTab] = useState("Overview");
  const [editOpen, setEditOpen] = useState(false);
  const employee = employees.find((item) => item.id === employeeId);
  const role = roles.find((item) => item.id === employee?.roleId);
  const assignedClients = clients.filter((client) => client.assignedToEmployeeId === employeeId);
  const employeeEvents = auditEvents.filter((event) => event.entityId === employeeId || assignedClients.some((client) => client.id === event.entityId));
  const effective = useMemo(() => employee ? getEffectivePermissions(employee, role) : new Set<PermissionKey>(), [employee, role]);
  if (!employee) return <div className="p-7"><EmptyState title="Employee not found" description="This employee is no longer present in the authenticated organization records." /><Link className="mt-4 inline-flex text-sm font-semibold text-primary" href="/employees">Return to employees</Link></div>;
  async function save(draft: EmployeeDraft) { const result = await updateEmployee(employeeId, draft); if (!result.ok) return result.error; setEditOpen(false); }
  return <div className="flex min-h-full w-full flex-col">
    <Link href="/employees" className="mb-5 inline-flex items-center gap-2 text-xs font-semibold text-muted-foreground hover:text-foreground"><ArrowLeft className="size-3.5" /> Employees</Link>
    <section className="rounded-xl border border-border bg-card p-5 shadow-xs"><div className="flex flex-col gap-5 sm:flex-row sm:items-center"><div className="grid size-16 shrink-0 place-items-center rounded-xl bg-primary/10 text-xl font-bold text-primary">{employee.name.split(" ").map((part) => part[0]).slice(0, 2).join("")}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h1 className="text-2xl font-semibold tracking-tight">{employee.name}</h1><StatusBadge tone={employee.status === "Active" ? "positive" : employee.status === "Disabled" ? "critical" : "warning"}>{employee.status}</StatusBadge>{employee.isSuperAdmin && <StatusBadge tone="navy">Privileged identity</StatusBadge>}</div><p className="mt-1 text-sm text-muted-foreground">{role?.name} · {employee.department} · {employee.employeeCode}</p><div className="mt-3 flex flex-wrap gap-x-5 gap-y-2 text-xs text-muted-foreground"><span className="flex items-center gap-1.5"><Mail className="size-3.5" />{employee.email}</span><span className="flex items-center gap-1.5"><Phone className="size-3.5" />{employee.phone}</span><span className="flex items-center gap-1.5"><MapPin className="size-3.5" />{employee.workspaceSlug}.psslogistics.in</span></div></div><div className="flex gap-2"><button onClick={() => setEditOpen(true)} className="flex h-9 items-center gap-2 rounded-xl border border-border px-3 text-xs font-semibold hover:bg-muted/40"><Pencil className="size-3.5" /> Edit</button>{!employee.isSuperAdmin && <button onClick={() => toggleEmployeeStatus(employee.id)} className="flex h-9 items-center gap-2 rounded-xl border border-destructive/25 px-3 text-xs font-semibold text-destructive hover:bg-destructive/10"><Ban className="size-3.5" />{employee.status === "Disabled" ? "Enable" : "Disable"}</button>}</div></div></section>
    <div className="mt-4 overflow-x-auto rounded-xl border border-border bg-card px-2 shadow-xs"><div className="flex min-w-max">{tabs.map((item) => <button key={item} onClick={() => setTab(item)} className={cn("border-b-2 px-4 py-3.5 text-xs font-semibold transition", tab === item ? "border-primary text-primary" : "border-transparent text-muted-foreground hover:text-foreground/80")}>{item}</button>)}</div></div>
    <div className="mt-4">{tab === "Overview" && <Overview employee={employee} roleName={role?.name ?? "—"} clients={assignedClients.length} effective={effective.size} />}{tab === "Permissions" && <Permissions catalog={permissionCatalog} employee={employee} effective={effective} onChange={(key, mode) => { void setPermissionOverride(employee.id, key, mode); }} />}{tab === "Clients" && <ClientList clients={assignedClients} />}{tab === "Activity" && <Activity events={employeeEvents} />}{tab === "Tickets" && <Placeholder icon={TicketCheck} title="Ticket responsibility" description={`${assignedClients.reduce((sum, client) => sum + client.openTickets, 0)} open tickets currently route through this employee's assigned clients.`} />}{tab === "Performance" && <Performance employeeName={employee.name} />}{tab === "Security" && <Security employee={employee} />}</div>
    <Modal open={editOpen} onClose={() => setEditOpen(false)} title="Edit employee" description={`Update ${employee.name}'s organization profile.`} size="lg"><EmployeeForm roles={roles} employee={employee} onSubmit={save} onCancel={() => setEditOpen(false)} /></Modal>
  </div>;
}

function Overview({ employee, roleName, clients, effective }: { employee: { joinedAt: string; lastActive: string; workspaceSlug: string }; roleName: string; clients: number; effective: number }) {
  const cards = [{ label: "Role", value: roleName, icon: ShieldCheck }, { label: "Assigned clients", value: String(clients), icon: Building2 }, { label: "Effective permissions", value: String(effective), icon: KeyRound }, { label: "Last active", value: employee.lastActive, icon: Clock3 }];
  return <div className="grid gap-4 lg:grid-cols-[1fr_.65fr]"><section className="rounded-xl border border-border bg-card p-5 shadow-xs"><h2 className="text-sm font-semibold">Access summary</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{cards.map(({ label, value, icon: Icon }) => <div key={label} className="rounded-xl bg-muted/40 p-4"><Icon className="size-4 text-primary" /><p className="mt-3 text-base font-semibold text-foreground">{value}</p><p className="mt-1 text-xs text-muted-foreground">{label}</p></div>)}</div></section><section className="rounded-xl border border-border bg-card p-5 shadow-xs"><h2 className="text-sm font-semibold">Workspace identity</h2><dl className="mt-4 space-y-4 text-xs"><div><dt className="text-muted-foreground">Workspace host</dt><dd className="mt-1 font-mono font-medium text-foreground/80">{employee.workspaceSlug}.psslogistics.in</dd></div><div><dt className="text-muted-foreground">Joined organization</dt><dd className="mt-1 font-medium text-foreground/80">{new Date(employee.joinedAt).toLocaleDateString("en-IN", { dateStyle: "medium" })}</dd></div><div><dt className="text-muted-foreground">Authentication</dt><dd className="mt-1 font-medium text-foreground/80">Supabase Auth identity · provisioned server-side</dd></div></dl></section></div>;
}

function Permissions({ catalog, employee, effective, onChange }: { catalog: Permission[]; employee: { isSuperAdmin?: boolean; permissionOverrides: { permissionKey: PermissionKey; mode: "grant" | "revoke" }[] }; effective: Set<PermissionKey>; onChange(key: PermissionKey, mode: "inherit" | "grant" | "revoke"): void }) {
  const groups = Array.from(new Set(catalog.map((permission) => permission.group)));
  if (employee.isSuperAdmin) return <section className="rounded-xl border border-primary/20 bg-primary/10 p-6"><div className="flex gap-3"><ShieldCheck className="size-5 text-primary" /><div><h2 className="text-sm font-semibold text-primary">Unrestricted system privilege</h2><p className="mt-1 text-xs leading-5 text-muted-foreground">Super Admin access bypasses individual permission assignment by policy. Permission overrides are intentionally unavailable for this identity.</p></div></div></section>;
  return <div className="space-y-4">{groups.map((group) => <section key={group} className="rounded-xl border border-border bg-card p-5 shadow-xs"><div className="mb-4 flex items-center justify-between"><h2 className="text-sm font-semibold">{group}</h2><span className="text-[11px] text-muted-foreground">{catalog.filter((permission) => permission.group === group && effective.has(permission.key)).length} effective</span></div><div className="divide-y divide-border/60">{catalog.filter((permission) => permission.group === group).map((permission) => { const override = employee.permissionOverrides.find((item) => item.permissionKey === permission.key)?.mode; return <div key={permission.key} className="flex flex-col gap-3 py-3 first:pt-0 last:pb-0 sm:flex-row sm:items-center"><div className="flex-1"><div className="flex items-center gap-2"><p className="text-xs font-semibold text-foreground">{permission.label}</p><code className="rounded bg-muted px-1.5 py-0.5 text-[9px] text-muted-foreground">{permission.key}</code></div><p className="mt-1 text-[11px] text-muted-foreground">{permission.description}</p></div><div className="flex rounded-lg bg-muted p-1">{(["inherit", "grant", "revoke"] as const).map((mode) => <button key={mode} onClick={() => onChange(permission.key, mode)} className={cn("rounded-md px-2.5 py-1 text-[10px] font-semibold capitalize", (override ?? "inherit") === mode ? mode === "grant" ? "bg-emerald-600 text-primary-foreground" : mode === "revoke" ? "bg-destructive text-primary-foreground" : "bg-card text-foreground/80 shadow-xs" : "text-muted-foreground")}>{mode}</button>)}</div><div className="w-20 text-right">{effective.has(permission.key) ? <span className="inline-flex items-center gap-1 text-[10px] font-bold text-emerald-600"><Check className="size-3" /> Effective</span> : <span className="inline-flex items-center gap-1 text-[10px] font-bold text-muted-foreground"><X className="size-3" /> Denied</span>}</div></div>; })}</div></section>)}</div>;
}

function ClientList({ clients }: { clients: ReturnType<typeof useAdmin>["clients"] }) { return <section className="rounded-xl border border-border bg-card p-5 shadow-xs"><h2 className="text-sm font-semibold">Assigned clients</h2>{clients.length ? <div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{clients.map((client) => <div key={client.id} className="rounded-xl border border-border/60 bg-muted/50 p-4"><div className="flex justify-between"><div><p className="text-xs font-semibold">{client.name}</p><p className="mt-1 text-[11px] text-muted-foreground">{client.code} · {client.city}</p></div><StatusBadge tone={client.status === "Active" ? "positive" : "warning"}>{client.status}</StatusBadge></div><div className="mt-4 flex gap-4 text-[11px] text-muted-foreground"><span><strong className="text-foreground">{client.shipmentVolume}</strong> shipments</span><span><strong className="text-foreground">{client.openTickets}</strong> tickets</span></div></div>)}</div> : <div className="mt-4"><EmptyState title="No assigned clients" description="Assign clients from the Client Assignments workspace." /></div>}</section>; }

function Activity({ events }: { events: ReturnType<typeof useAdmin>["auditEvents"] }) { return <section className="rounded-xl border border-border bg-card p-5 shadow-xs"><h2 className="text-sm font-semibold">Related activity</h2><div className="mt-4 divide-y divide-border/60">{events.length ? events.map((event) => <div key={event.id} className="flex gap-3 py-3"><div className="mt-1 size-2 rounded-full bg-primary ring-4 ring-primary/10" /><div><p className="text-xs font-semibold">{event.action}</p><p className="mt-1 text-[11px] text-muted-foreground">{event.entityLabel} · {new Date(event.timestamp).toLocaleString("en-IN")}</p></div></div>) : <p className="text-xs text-muted-foreground">No related audit activity.</p>}</div></section>; }

function Placeholder({ icon: Icon, title, description }: { icon: typeof TicketCheck; title: string; description: string }) { return <section className="rounded-xl border border-border bg-card p-8 shadow-xs"><div className="grid size-10 place-items-center rounded-xl bg-muted text-muted-foreground"><Icon className="size-5" /></div><h2 className="mt-4 text-sm font-semibold">{title}</h2><p className="mt-1 max-w-xl text-xs leading-5 text-muted-foreground">{description}</p></section>; }
function Performance({ employeeName }: { employeeName: string }) { return <Placeholder icon={UserRound} title="Performance snapshot" description={`${employeeName}'s production activity is available in the Activity and Tickets tabs. Aggregated performance scoring will appear after sufficient operational events exist.`} />; }
function Security({ employee }: { employee: { email: string; status: string } }) { return <section className="grid gap-4 md:grid-cols-2"><Placeholder icon={KeyRound} title="Authentication status" description={`${employee.email} is managed through Supabase Auth. Password reset and session controls follow the configured organization authentication policy.`} /><Placeholder icon={ShieldCheck} title="Access state" description={`Current organization access is ${employee.status.toLowerCase()}. Role and permission changes are enforced through the server-side permission catalog.`} /></section>; }

