"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { MoreHorizontal, Plus, Search, ShieldCheck, UserRoundCheck, UsersRound } from "lucide-react";
import { useAdmin } from "@/components/admin/admin-provider";
import { EmployeeForm } from "@/components/admin/employee-form";
import { EmptyState, inputClass, Modal, StatusBadge } from "@/components/admin/ui";
import type { EmployeeDraft } from "@/lib/admin-domain";
import { cn } from "@/lib/utils";

export default function EmployeesPage() {
  const { employees, roles, clients, createEmployee, toggleEmployeeStatus } = useAdmin();
  const [query, setQuery] = useState("");
  const [status, setStatus] = useState("All");
  const [createOpen, setCreateOpen] = useState(false);
  const [menuId, setMenuId] = useState<string | null>(null);
  const filtered = useMemo(() => employees.filter((employee) => (status === "All" || employee.status === status) && `${employee.name} ${employee.email} ${employee.employeeCode} ${employee.department}`.toLowerCase().includes(query.toLowerCase())), [employees, query, status]);
  const counts = { active: employees.filter((employee) => employee.status === "Active").length, invited: employees.filter((employee) => employee.status === "Invited").length, disabled: employees.filter((employee) => employee.status === "Disabled").length };
  useEffect(() => {
    const close = (event: PointerEvent) => { if (!(event.target as Element).closest("[data-employee-menu]")) setMenuId(null); };
    const escape = (event: KeyboardEvent) => { if (event.key === "Escape") setMenuId(null); };
    document.addEventListener("pointerdown", close); document.addEventListener("keydown", escape);
    return () => { document.removeEventListener("pointerdown", close); document.removeEventListener("keydown", escape); };
  }, []);
  function submit(draft: EmployeeDraft) { const result = createEmployee(draft); if (!result.ok) return result.error; setCreateOpen(false); }
  return <div className="flex min-h-full w-full flex-col">
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h1 className="text-2xl font-semibold tracking-[-0.03em] text-foreground">Employees</h1><p className="mt-1 text-sm text-muted-foreground">Manage identities, responsibilities, and internal access.</p></div><button onClick={() => setCreateOpen(true)} className="flex h-10 items-center justify-center gap-2 rounded-xl bg-primary px-4 text-sm font-semibold text-primary-foreground shadow-sm hover:bg-primary/90"><Plus className="size-4" /> Create employee</button></div>
    <section className="mt-6 grid gap-3 sm:grid-cols-3">{[{ label: "Active employees", value: counts.active, icon: UserRoundCheck, color: "text-emerald-600 bg-emerald-500/10" }, { label: "Pending invitations", value: counts.invited, icon: UsersRound, color: "text-amber-600 bg-amber-500/10" }, { label: "Access roles", value: roles.length, icon: ShieldCheck, color: "text-primary bg-primary/10" }].map(({ label, value, icon: Icon, color }) => <article key={label} className="flex items-center gap-4 rounded-xl border border-border bg-card p-4 shadow-xs"><div className={cn("grid size-10 place-items-center rounded-xl", color)}><Icon className="size-[18px]" /></div><div><p className="text-xl font-semibold">{String(value).padStart(2, "0")}</p><p className="text-xs text-muted-foreground">{label}</p></div></article>)}</section>
    <section className="mt-4 flex min-h-0 flex-1 flex-col overflow-visible rounded-xl border border-border bg-card shadow-xs"><div className="flex flex-col gap-3 border-b border-border/60 p-4 sm:flex-row sm:items-center"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><input value={query} onChange={(event) => setQuery(event.target.value)} className={cn(inputClass, "pl-9")} placeholder="Search name, ID, email, or department" /></div><div className="flex rounded-xl bg-muted p-1">{["All", "Active", "Invited", "Disabled"].map((item) => <button key={item} onClick={() => setStatus(item)} className={cn("rounded-lg px-3 py-1.5 text-xs font-semibold", status === item ? "bg-card text-foreground shadow-xs" : "text-muted-foreground")}>{item}</button>)}</div></div>
      {filtered.length === 0 ? <div className="p-4"><EmptyState title="No employees found" description="Try a different search or status filter." /></div> : <div className="overflow-x-auto"><table className="w-full min-w-[1180px] text-left"><thead><tr className="border-b border-border/60 bg-muted/60 text-[10px] font-bold uppercase tracking-[0.1em] text-muted-foreground">{["Employee", "Role / Department", "Workspace", "Clients", "Status", "Last active", ""].map((header) => <th key={header} className="px-4 py-3">{header}</th>)}</tr></thead><tbody className="divide-y divide-border/60">{filtered.map((employee) => { const role = roles.find((item) => item.id === employee.roleId); const assigned = clients.filter((client) => client.assignedToEmployeeId === employee.id).length; return <tr key={employee.id} className="group hover:bg-muted/60"><td className="px-4 py-3.5"><Link href={`/employees/${employee.id}`} className="flex items-center gap-3"><div className="grid size-9 place-items-center rounded-xl bg-muted text-xs font-bold text-muted-foreground">{employee.name.split(" ").map((part) => part[0]).slice(0, 2).join("")}</div><div><p className="text-sm font-semibold text-foreground group-hover:text-primary">{employee.name}</p><p className="mt-0.5 text-[11px] text-muted-foreground">{employee.employeeCode} · {employee.email}</p></div></Link></td><td className="px-4 py-3.5"><p className="text-xs font-medium text-foreground/80">{role?.name}</p><p className="mt-0.5 text-[11px] text-muted-foreground">{employee.department}</p></td><td className="px-4 py-3.5"><p className="font-mono text-[11px] text-muted-foreground">{employee.workspaceSlug}.psslogistics.in</p></td><td className="px-4 py-3.5 text-xs font-semibold text-foreground/80">{assigned}</td><td className="px-4 py-3.5"><StatusBadge tone={employee.status === "Active" ? "positive" : employee.status === "Disabled" ? "critical" : "warning"}>{employee.status}</StatusBadge></td><td className="px-4 py-3.5 text-xs text-muted-foreground">{employee.lastActive}</td><td data-employee-menu className="relative px-4 py-3.5"><button onClick={() => setMenuId(menuId === employee.id ? null : employee.id)} aria-label={`Actions for ${employee.name}`} className="rounded-lg p-2 text-muted-foreground hover:bg-muted hover:text-foreground/80"><MoreHorizontal className="size-4" /></button>{menuId === employee.id && <div className="absolute right-8 top-11 z-20 w-44 rounded-xl border border-border bg-card p-1.5 shadow-xl"><Link href={`/employees/${employee.id}`} className="block rounded-lg px-3 py-2 text-xs font-medium hover:bg-muted/40">View employee</Link>{!employee.isSuperAdmin && <button onClick={() => { toggleEmployeeStatus(employee.id); setMenuId(null); }} className="w-full rounded-lg px-3 py-2 text-left text-xs font-medium text-destructive hover:bg-destructive/10">{employee.status === "Disabled" ? "Enable access" : "Disable access"}</button>}</div>}</td></tr>; })}</tbody></table></div>}
    </section>
    <Modal open={createOpen} onClose={() => setCreateOpen(false)} title="Create employee" description="Create an internal identity and initial workspace access." size="lg"><EmployeeForm roles={roles} onSubmit={submit} onCancel={() => setCreateOpen(false)} /></Modal>
  </div>;
}
